Algoritmo "semnome"
// Disciplina: [Linguagem e Lógica de programaçao] 
// Professor: Antonio Carlos Nicolodi
// Autor : Cláudio
// Data : 21/06/2015
// Seção de Declarações 
var
   i, a : inteiro
   x : real
   matriz : vetor[1..15] de real
inicio
// Seção de Comandos 
i := 1
repita
     x := randi(25)
     matriz[i] := x
     i := i + 1
ate i = 15

Para a de 1 ate 15 faça

Escreva ("[",matriz[a], "]   ")

FimPara

fimalgoritmo
